- .github/workflows/formatting.yaml
My copypasta from the ci yaml left the formatting job with the name 'cargo test'. This causes confusion when looking at the  actions in the github UI.
> ci: Rename formatting action to resolve ambiguity.

- .github/workflows/ci.yaml
This causes the action to fail when a clippy lint classified as a warning is found. Lint groups complexity, perf, style and suspicious are all reported as warnings according to:
https://rust-lang.github.io/rust-clippy/
> Give clippy some teeth.

- Cargo.lock
This fixes a known issue introduced in rust 1.69 clippy that required additional changes to clap. See:
https://github.com/rust-lang/rust-clippy/issues/10421
https://github.com/clap-rs/clap/issues/4733
this resolves #28
> Update clap to 4.1.11.

- ca-script/ca-setup.sh
This makes debugging easier. Would be nice to have a PEM encoded version of the cert after it's been through the templating thing.
> ca-script: copy PEM certs to tmpls

- ca-script/ca-setup.sh
We're not doing anything with these yet and when unused they generate a pile of compiler warnings. Don't turn them on till we figure out what we're doing with them.
> ca-script: stop generating offsets for issuer & subject CNs

- Cargo.lock
- dice-mfg-msgs/Cargo.toml
- dice-mfg-msgs/src/lib.rs
- dice-mfg/Cargo.toml
- dice-mfg/src/lib.rs
Implementing 'Error' requires we implement 'Display' so we use this to replace some of the ill advised stuff I was doing with 'to_str()'.
> dice-mfg-msgs: Add 'std' feature, use thiserror when its enabled.

- dice-mfg-msgs/src/lib.rs
I'm not sure I like this better than the by hand implementation. If nothing else it ties the 'Display' implementation to the `std` feature where before it was applicable regardless. Not sure why I'd need the 'Display' implementation in a `no_std` environment though.
> Thiserror display

- Cargo.lock
- dice-mfg/Cargo.toml
- dice-mfg/src/lib.rs
- dice-mfg/src/main.rs
The object-id for the auth credential (auth-id) and the associated password get combined as a hack to plumb this data through the PKCS#11 auth APIs. It would have been more simple for us to just have whatever sets the password in the environment to include the object-id of the auth token too. Somehow passing the auth-id and then combining them programatically felt more natural.
This resolves #44
> dice-mfg: Get password from env, allow caller to set auth-id used.

- Cargo.lock
- dice-mfg/Cargo.toml
- dice-mfg/src/lib.rs
- dice-mfg/src/main.rs
This pulls in the yubihsm crate to get the `object::Id` type. All use of the `auth_id` is moved into the CertSigner including setting up the PKCS11 auth environment variable that includes the concatenation of the `auth_id` and the auth value.
> Add 'auth_id' as member of CertSigner.

- Cargo.lock
- dice-mfg/Cargo.toml
- dice-mfg/src/lib.rs
- dice-mfg/src/main.rs
NOTE: This commit uses a fork of yubihsm.rs with local changes to work around a bug in their serialization of a 'special' audit entry.
this resolves #65
> Add command to dump audit log & advance index, so same after each sign.

- dice-mfg/src/main.rs
We only use these prefixes for params we expect the mfg programming station to set.
> Use environment variables prefixed with `DICE_MFG_`.

- dice-mfg/src/main.rs
Files holding CSRs are named according to their platform id w/ the 'csr.pem' suffix.
> Save CSRs from devices being manufactured to the 'csr' ca-state dir.

- dice-mfg/src/lib.rs
- dice-mfg/src/main.rs
Additionally we no longer export the `ENV_PASSWD_PKCS11` constant to make it clear that it's only used internal to the module.
> Fix misleading comments on env var strings for passwords.

- dice-mfg/src/lib.rs
- dice-mfg/src/main.rs
Depending on use-case we may want a `--force` option to change the default behavior of refusing to overwrite files in `--work-dir`.
> Add option to save CSR & cert to a user supplied directory.

- Cargo.lock
- dice-mfg-msgs/src/lib.rs
- dice-mfg/Cargo.toml
- dice-mfg/src/lib.rs
This allows us to check that the RoT received any message that responds with Ack. This includes all of the messages that we care about including: the platforms unique id, it's identity cert and the cert for the issuing intermediate CA. All other messages that require an Ack (Break & Ping) will reply with 32 bytes of 0's.
> Add sha3-256 hash to Ack message as integrity check.

- Cargo.lock
- dice-mfg-msgs/src/lib.rs
- dice-mfg/Cargo.toml
- dice-mfg/src/lib.rs
- dice-mfg/src/main.rs
This 'policy' is currently limited to ensuring that the 'subject' Name contains the expected PlatformId in the 'cn' / 'commonName' RDN. OpenSSL performs additional checks before signing the cert and these are defined by the OpenSSL config file.
This resolves #64
> Implement policy check for CSR received from RoT.

- .gitignore
- Cargo.lock
- dice-mfg-msgs/Cargo.toml
- dice-mfg-msgs/src/lib.rs
- dice-mfg/Cargo.toml
- dice-mfg/src/lib.rs
- dice-mfg/src/main.rs
- dice-mfg-msgs: messages to query key slot status
- dice-mfg: subcommand to query key slot status
- dice-mfg manufacture: require device is in release configuration before starting
- fix
- dice-mfg: bump version
- .gitignore: ignore Rust target/ directory
> Check release config before manufacturing

- Cargo.lock
- Cargo.toml
- dice-cert-check/Cargo.toml
- dice-cert-check/src/lib.rs
- dice-cert-check/src/main.rs
- dice-mfg/Cargo.toml
progress on #91: Update `dice-cert-check` to use workspace dependencies. The hard part of this was getting it to use releases for  `const-oid`, `pem-rfc7468` and `x509-cert`.
> Cert check dep cleanup

- Cargo.lock
- Cargo.toml
- verifier/Cargo.toml
- verifier/src/main.rs
The goal is to make this tool capable of talking to the Attest direcly or through the Sprot proxy. The initial implementation is limited to the simple commands that return integers. All other of the more complex commands are left as `todo!`s. Eventually a `verify` command will follow.
> Add tool to verify attestations from the Attest task.

- Cargo.lock
- attest-data/Cargo.toml
- attest-data/src/lib.rs
- verifier/src/main.rs
The current version of curve25519-dalek uses rust features that aren't available in the compiler version pinned by hubris. Since we're only using one type and one constant from dalek it's easily replaced by the salty crate.
> attest-data: Remove dependency on ed25519-dalek, use salty instead.

- verifier-cli/src/main.rs
this is useful now that https://github.com/oxidecomputer/hubris/pull/1587 and https://github.com/oxidecomputer/humility/pull/438 have been merged
> verifier-cli: Port attest command to lease-based hiffy interface.

- Cargo.lock
This is required to get curve25519-dalek to build on the 1.78 nightly compiler. The previous version will cause complaints about use of unstable features.
this resolves #176
> build: Upgrade the dalek libraries.

- dice-mfg-msgs/src/lib.rs
this gets us a green light on CI w/ the latest nightly clippy
> dice-mfg-msgs: Remove unnecessary `use core::convert::TryFrom`.

- dice-mfg/src/main.rs
Previously if this param was omitted the `manufacture` command would attempt to find the intermediate CA cert in the place the `oks` software stores it by convention. This was the right thing to do for FCS but now that we're attempting to support multiple CA interfaces this behavior requires knowledge of not just openssl but the specific configuration and filesystem structure created by OKS.
This commit makes this parameter required removing the OKS / openssl specific knowledge from the `manufacture` command / interface. This will break consumers that relied on the old default behavior. This param will be required until we implement a mechanism to get this info from the CAs we support.
> manufacture: `intermediate-cert` param is now required

- Cargo.lock
- Cargo.toml
- dice-mfg/Cargo.toml
- dice-mfg/src/lib.rs
- dice-mfg/src/main.rs
I spent some time banging my head against clap trying to get a better CLI for this and came up short. There's likely a way to accomplish this through the clap API but for now I'm just stuffing the config params required by each CA into a single `String` param that's formatted as key=value,....
this resolves #112
> Add structure to support CAs beyond `openssl ca`

- Cargo.lock
- Cargo.toml
- dice-mfg/Cargo.toml
- dice-mfg/src/main.rs
~~NOTE: Depends on [permslip#165](https://github.com/oxidecomputer/permission-slip/pull/165); if you test locally, be sure to build `permslip` from that branch.~~
Reverts a few aspects of 26dae63f2c2bc6c026a505b1c938c3077daa8007, in particular the shell expansion and key-value encoding of arguments. Instead, we use a clap `Subcommand` for signing, which can be either `openssl` or `permslip`:
```
$ dice-mfg sign-cert --help                                        
Turn a CSR into a cert. This is a thin wrapper around either the `openssl ca` command (whose behavior will depend on the openssl.cnf provided by the caller), or `permslip sign` (whose behavior will be governed by a previously set key context and batch of approvals)
Usage: dice-mfg sign-cert [OPTIONS] --cert-out <CERT_OUT> <CSR_IN> …
```
> Permslip signing backend

- dice-mfg/src/main.rs
`facade` prefers to use the environment to pass stuff
> Allow callers to provide the permslip key name through the environment

- dice-mfg/Cargo.toml
This is a minor version bump to reflect new features and incompatible changes w/ the 0.1.1 version.
> dice-mfg: bump version 0.1.1 -> 0.2.0

- .github/workflows/ci.yaml
- Cargo.lock
This is what we wanted in the first place. It has the added benefit of causing an error if / when the Cargo.lock file gets updated and it shouldn't.
> Add `--locked` flag to CI test run.

- Cargo.lock
- verifier-cli/Cargo.toml
- verifier-cli/src/main.rs
- verifier/Cargo.toml
- verifier/src/lib.rs
This makes it easier and more explicit to use as a library in other crates such as sprockets.
> Rename `verifier` crate to `dice-verifier`

- verifier-cli/src/main.rs
Allowing the caller to provide the path makes scripting this much easier.
> verifier-cli: Replace --persist w/ --work-dir in `verify` command.

- Cargo.lock
- verifier-cli/Cargo.toml
- verifier-cli/src/main.rs
This falls short of removing all binary encodings but it makes it possible for us to use the `verify` command to verify an attestation and persist the artifacts as JSON. Later we can use the `verify-attestation` and `verify-cert-chain` commands to re-verify the artifacts persisted by the `verify` command.
Other commands like `attest` and `log` still need to be updated to use the JSON encoding.
> verifier-cli: Persist artifacts as json instead of raw binary.

- verifier-cli/src/main.rs
We don't pretty print the json because it's mostly arrays and that gets us a newline after each element and that's arguably worse. This at least gets us valid text files in the eyes of POSIX.
> Add a newline to json output.

- Cargo.lock
- attest-data/Cargo.toml
- attest-data/src/messages.rs
- dice-cert-tmpl/src/cert.rs
- dice-cert-tmpl/src/csr.rs
The name `SprotError` is already used in hubris. This is technically fine but is causing some conflicts with our other tooling. Change the name to avoid conflicts.
> Change error name to avoid hiffy conflict

- attest-data/src/lib.rs
Right now, it is literally impossible to get anything out of a `MeasurementLog`: its members are private, and it has no accessor functions.
This PR adds `len()`, `is_empty()`, and `core::ops::Index` implementations.
> Add functions to get measurements out of the log

- verifier-cli/README.md
- verifier-cli/src/main.rs
This resolves two inconsistencies in the tool that made the instructions in the README inaccurate. The verification functions were updated to operate only on JSON encoded data. The `attest` and `log` commands still produced binary data however which prevented the verification command to operate on their output. This PR updates the `attest` and `log` commands to produce JSON.
> Consistent encoding

- .github/workflows/ci.yaml
The resolver unifies features when building packages in the workspace. This prevents a single invocation of `cargo build --workspace` from building 'no_std' versions of the libraries here. Adding an explicit build command for our libraries that have 'std' features ensures that we catch errors that break the build if 'std' is not enabled.
> Add explicit build step to build the workspace and no_std libs

- Cargo.lock
- dice-mfg-msgs/Cargo.toml
- dice-mfg-msgs/src/lib.rs
- verifier-cli/Cargo.toml
- verifier-cli/src/main.rs
This is useful for pulling the PlatformId out of the cert chain produced by the RoT.
> dice-mfg-msgs: Impliment PlatformId::TryFrom<&PkiPath>

- verifier-cli/src/hiffy.rs
- verifier-cli/src/main.rs
`Interface` is doing double duty as the variants we accept for a particular parameter as well as configuring how we instantiate the `AttestHiffy` type. Having a separate type for each is better.
> verifier-cli: Break dependency from `hiffy` module on `Interface.

- Cargo.lock
This gets us to a version of this library where RUSTSEC-2024-0344 has been resolved.
> Update curve25519-dalek to 4.1.3.

- Cargo.lock
- verifier/Cargo.toml
- verifier/src/lib.rs
- verifier/src/mock.rs
Mostly this just returns data that's populated when the type is instantiated. The only interesting code is in the `attest` function where we generate the attestation from the artifacts provided.
> Add a mock implementation of the `Attest` trait.
